import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import "./../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-zinc-100")}>
        <div className="flex">
          <div className="h-screen w-[260px] p-8">
            <div className="text-2xl font-bold mb-10 uppercase text-red-700">My app</div>
            <div>
              <div className="font-semibold">Dashboard</div>
            </div>
          </div>
          <div className="p-10 flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
